package agent

import (
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const wrappedClaudeProbeBytes = 8 * 1024

// Agent describes how AGX invokes a supported coding agent for run, resume, and
// print-style commands.
type Agent struct {
	Name        string
	Command     string
	Args        []string
	ResumeArgs  []string
	PrintArgs   []string
	Description string
	Env         map[string]string
}

// IsAvailable reports whether the configured command is executable on PATH.
func (a Agent) IsAvailable() bool {
	_, err := exec.LookPath(a.Command)
	return err == nil
}

// ShouldInjectInitialPrompt reports whether AGX should wait for an interactive
// composer and paste the first prompt instead of passing it as argv. This is
// needed for wrapped Claude binaries that do not accept a prompt argument.
func (a Agent) ShouldInjectInitialPrompt() bool {
	return a.Name == "claude" && len(a.Args) == 0 && isWrappedClaudeCommand(a.Command)
}

// BuildRunCommand returns the default all-mighty command for starting an agent
// with prompt.
func (a Agent) BuildRunCommand(prompt string) []string {
	return a.BuildRunCommandMode(prompt, true)
}

// BuildRunCommandMode returns argv for starting an agent. The prompt is always a
// single argument when supported, never shell-split by AGX.
func (a Agent) BuildRunCommandMode(prompt string, allMighty bool) []string {
	if a.ShouldInjectInitialPrompt() {
		prompt = ""
	}
	if len(a.Args) > 0 {
		args := append([]string{a.Command}, a.Args...)
		if prompt != "" {
			args = append(args, prompt)
		}
		return args
	}
	var args []string
	switch a.Name {
	case "claude":
		args = []string{a.Command}
		if allMighty {
			args = append(args, a.claudeAllMightyArgs()...)
		}
		if prompt != "" {
			args = append(args, prompt)
		}
	case "codex":
		args = []string{a.Command}
		if allMighty {
			args = append(args, sandboxDisableArgs()...)
			args = append(args, "--dangerously-bypass-approvals-and-sandbox")
		}
		if prompt != "" {
			args = append(args, prompt)
		}
	case "gemini":
		args = []string{a.Command}
		if allMighty {
			args = append(args, "--approval-mode", "yolo")
		}
		if prompt != "" {
			args = append(args, "-i", prompt)
		}
	case "cursor":
		args = []string{a.Command}
		if allMighty {
			args = append(args, "--yolo")
		}
		if prompt != "" {
			args = append(args, prompt)
		}
	case "copilot":
		args = []string{a.Command}
		if allMighty {
			args = append(args, "--allow-all-tools")
		}
		if prompt != "" {
			args = append(args, "-p", prompt)
		}
	case "opencode":
		args = []string{a.Command}
		if prompt != "" {
			args = append(args, "-p", prompt)
		}
	default:
		args = append([]string{a.Command}, a.Args...)
		if prompt != "" {
			args = append(args, prompt)
		}
	}
	return args
}

// BuildResumeCommand returns the default all-mighty command for resuming the
// most recent agent session.
func (a Agent) BuildResumeCommand() []string {
	return a.BuildResumeCommandMode(true)
}

// BuildResumeCommandMode returns argv for resuming an agent session.
func (a Agent) BuildResumeCommandMode(allMighty bool) []string {
	if len(a.ResumeArgs) > 0 {
		return append([]string{a.Command}, a.ResumeArgs...)
	}
	switch a.Name {
	case "claude":
		args := []string{a.Command}
		if allMighty {
			args = append(args, a.claudeAllMightyArgs()...)
		}
		return append(args, "--continue")
	case "codex":
		args := []string{a.Command}
		if allMighty {
			args = append(args, sandboxDisableArgs()...)
			args = append(args, "--dangerously-bypass-approvals-and-sandbox")
		}
		return append(args, "resume", "--last")
	case "gemini":
		args := []string{a.Command}
		if allMighty {
			args = append(args, "--approval-mode", "yolo")
		}
		return append(args, "--resume")
	case "cursor":
		args := []string{a.Command}
		if allMighty {
			args = append(args, "--yolo")
		}
		return append(args, "--continue")
	case "opencode":
		return []string{a.Command, "--continue"}
	default:
		return []string{a.Command}
	}
}

func (a Agent) claudeAllMightyArgs() []string {
	// Claude sandboxes its Bash tool on every OS now, so all-mighty always
	// disables the OS sandbox (where one exists) in addition to skipping
	// permission prompts. The flag is a no-op/valid where the sandbox is not
	// applied. Wrapped vs plain Claude only affects prompt injection, not flags.
	return append(sandboxDisableArgs(), "--dangerously-skip-permissions")
}

// isWrappedClaudeCommand detects Claude wrappers generated by desktop app
// bundles. Those wrappers need prompt injection because argv prompt passing
// would be consumed by the wrapper rather than Claude itself.
func isWrappedClaudeCommand(command string) bool {
	if command == "" {
		return false
	}
	path := command
	if resolved, err := exec.LookPath(command); err == nil {
		path = resolved
	}
	if strings.Contains(path, "claude_code") {
		return true
	}
	if resolved, err := filepath.EvalSymlinks(path); err == nil && strings.Contains(resolved, "claude_code") {
		return true
	}
	file, err := os.Open(path)
	if err != nil {
		return false
	}
	defer file.Close()
	data, err := io.ReadAll(io.LimitReader(file, wrappedClaudeProbeBytes))
	if err != nil {
		return false
	}
	return strings.Contains(string(data), "claude_code")
}

// BuildPrintCommand returns argv for one-shot non-interactive output where the
// agent supports it.
func (a Agent) BuildPrintCommand(prompt string) []string {
	if len(a.PrintArgs) > 0 {
		args := append([]string{a.Command}, a.PrintArgs...)
		if prompt != "" {
			args = append(args, prompt)
		}
		return args
	}
	switch a.Name {
	case "claude":
		return []string{a.Command, "--print", prompt}
	case "codex":
		args := []string{a.Command}
		args = append(args, sandboxDisableArgs()...)
		return append(args, "exec", "--dangerously-bypass-approvals-and-sandbox", prompt)
	case "gemini":
		return []string{a.Command, "-p", prompt}
	case "cursor":
		return []string{a.Command, "--print", "--yolo", prompt}
	case "copilot":
		return []string{a.Command, "--allow-all-tools", "-p", prompt}
	case "opencode":
		return []string{a.Command, "-p", prompt}
	default:
		args := []string{a.Command}
		if prompt != "" {
			args = append(args, prompt)
		}
		return args
	}
}
